test:
  - test/**

backend:
  - lib/**/*.ex
  - web/**/*.ex

frontend:
  - web/static/**/*
  - web/views/**/*

documentation:
  - /**/*.md

dependencies:
  - package.json
  - yarn.lock
  - /**/package.json
  - /**/yarn.lock
  - mix.exs
  - mix.lock

chore:
  - .github/**/*
  - priv/**/*.ex
  - priv/**/*.exs